### ISSUE TITLE
feature request: proxy TCP / UDP connection with SOCKS4 / SOCKS5. 

### ISSUE THREAD

**Issue by VergeDX** [0x0ade/CelesteNet#116]
I live in China and [GFW](https://en.wikipedia.org/wiki/Great_Firewall) will block connection between me and the server : (  
Usually we browse internet with HTTP proxy, but the mod uses TCP connection.  
I'm digging in CelesteNet source code, maybe I will do a PR later : )

**Comment by RedFlames** [comment]
Are you aware of the Chinese fork of Celestenet? There's a server somewhere hosted by @WEGFan although I'm unsure where go find more information about it, actually.
Maybe getting MiaoCelesteNet, possibly from here?
https://celestenyaserver.github.io/CelesteMiaoServer.Wiki/#/zh-cn/Celeste/Mods/Functional_mod_list
I didn't manage to get Google to translate that site for me on my phone and I can't read Chinese.
Also, @CelesteNyaServer here on Github maybe
Hopefully some of this will point you in the right direction, if you weren't aware already.

If you just really want to connect to "regular" Celestenet instead, atm I'm not sure how this would be implemented, would it only be a Client change? :thinkeline:

**Comment by WEGFan** [comment]
If you want to play with people in Chinese community, you can download [Chinese fork](https://celeste.weg.fan/api/v2/download/mods/Miao.CelesteNet.Client) and check out the tutorial on registering an account [here](https://celeste.centralteam.cn/d/5-qun-fu-zhu-ce-zhi-nan). The fork added IME support so you can input Chinese in the chat box.

I am the former maintainer of the mod, now it's maintained by someone else.

If you still want to use the official server, maybe try using Proxifier to force the game to use proxy or enabling system proxy.

**Comment by RedFlames** [comment]
This is pretty old and it is highly unlikely to be added to the Client on our side, unless it would be really trivial to drop in the socket thing somehow and someone made a PR. But really I hope you found your way onto Miao.CelesteNet last year and I'm closing this for now :)
