### ISSUE TITLE
Connection failed

### ISSUE THREAD

**Issue by ManaNz17** [0x0ade/CelesteNet#156]
It's not my case but it's from a friend who I'm introducing to Celeste, he's done everything correctly like the rest of the group (we're 4), but when he finally goes to connect it just shows up "connection failed", even if he turns off "Receive Player Avatars" or even tries to connect as a guest, so far I have not been able to find a solution even trying basic things such as unninstalling and installing the mod again or restarting the pc. I kinda hope this can be quickly fixed since we're waiting on everyone to be able to play so they can all experience the game together the same way I did in my first time.

**Comment by RedFlames** [comment]
I assume v2.4.1 fixed things? 🐈
