### ISSUE TITLE
Hair not updating correctly

### ISSUE THREAD

**Issue by slipsy** [0x0ade/CelesteNet#42]
Been messing around a bit with some friends. In regards to hair lengths, 99% of the time, everyone's hair displays as the default length of 4, regardless of length it's been set to (there has been one-off exceptions but i'm not sure how these have happened). Entering and then exiting pico-8 from within the celestial resort however allows other users to see the correct length, until you return to the map. Also, wind effect on hair has the inverse issue, where it is not updated by entering pico-8 but is updated by returning to the map.

**Comment by RedFlames** [comment]
This is now officially fixed with the release of v2.1.0 today. ✅
